import { SimpleGrid } from "@mantine/core"
import Head from "next/head"
import { trpc } from "../utils/trpc"
import styles from "./index.module.css"
import BlocComponent from "../components/BlocComponent"

export default function Home() {
  const { data, error } = trpc.bloc.getByCode.useQuery({ code: 'FORMULAIRE_INSCRIPTION' })
  const { data: blocTeletravail } = trpc.bloc.getByCode.useQuery({ code: 'FORMULAIRE_TELETRAVAIL' })

  if (error || !data ) return <></>
  return (
    <>
      <Head>
        <title>React dynamic form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerOuter}>
        <div className={styles.containerInner}>
          <h1 className={styles.title}>
            <span className={styles.titlePink}>Dynamic form</span>
          </h1>

          <div>
            <SimpleGrid cols={3}>
              {data && <BlocComponent id={data.id} code={data.code} description={data.description} inputs={data.inputs} title={data.title} />}
              {blocTeletravail && <BlocComponent id={blocTeletravail.id} code={blocTeletravail.code} description={blocTeletravail.description} inputs={blocTeletravail.inputs} title={blocTeletravail.title} />}

            </SimpleGrid>
          </div>

        </div>
      </div>
    </>
  )
}


